name: continuous_integration_delivery

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update package manager & install make python3 pip pipenv
      run: |
        sudo apt update -y
        sudo apt install -y make python3 python3-setuptools python3-pip
        sudo pip3 install pipenv
        sudo pip3 install wheel
        make install_requirements_dev
    
    - name: tests
      run: make tests
      
    - name: build
      run: |
        make clean
        make install_requirements
        make dist
      
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}

    - name: deploy
      run: aws s3 sync dist/ s3://${{ secrets.AWS_BUCKET_NAME }}/bundle/ --delete
